apiVersion: v1
kind: ConfigMap
metadata:
  name: payloadapi-config
  namespace: payloadapi-dev
  labels:
    app: payloadapi
    environment: dev
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
