apiVersion: v1
kind: ConfigMap
metadata:
  name: payloadapi-config
  namespace: payloadapi-local
  labels:
    app: payloadapi
    environment: local
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Logging__LogLevel__Default: "Debug"
  Logging__LogLevel__Microsoft.AspNetCore: "Information"
