apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payloadapi-ingress
  namespace: payloadapi-local
  labels:
    app: payloadapi
    environment: local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: payloadapi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payloadapi
            port:
              number: 80
