apiVersion: v1
kind: ConfigMap
metadata:
  name: payloadapi-config
  namespace: payloadapi-prod
  labels:
    app: payloadapi
    environment: prod
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Warning"
  Logging__LogLevel__Microsoft.AspNetCore: "Error"
