apiVersion: v1
kind: Service
metadata:
  name: payloadapi
  namespace: payloadapi-prod
  labels:
    app: payloadapi
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: payloadapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
